# Generated by Django 5.1.1 on 2024-09-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_customer_role_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
